"""Natural-sounding phrasing variants per task category, across all 6
languages (en, de, fr, es, it, nl).

Two generation strategies, mixed deliberately:
- Sprint 1's four categories (word_center, word_bbox, line_start, line_end)
  keep their original hand-written, fully-formed per-language sentences
  (highest phrasing quality, no compositional risk).
- The ~30 categories added in Sprint 3 are generated by composing a small
  set of translated verb frames (point vs. bbox) with a translated "referent"
  noun phrase per category. This keeps the per-language translation surface
  small and mechanical while still producing genuine, distinct text per
  category/language, and deliberately avoids embedding relative clauses
  ("the line that starts with...") in non-English frames, where naive
  word-for-word composition would read as broken grammar — referent phrases
  use simple noun-phrase or colon-delimited constructions instead. Minor
  case/declension imperfections in German/French/etc. noun phrases are an
  accepted scope simplification (training signal here is about visual
  grounding, not grammatical perfection).
"""

TEMPLATES = {
    "word_center": {
        "en": [
            'Click on the word "{text}".',
            'Where is the word "{text}" located?',
            'Point to "{text}".',
            'Can you tap the word "{text}"?',
            'Select "{text}" on the page.',
            'I need you to find "{text}".',
        ],
        "de": [
            'Klicke auf das Wort "{text}".',
            'Wo befindet sich das Wort "{text}"?',
            'Zeige auf "{text}".',
            'Kannst du "{text}" antippen?',
            'Wähle "{text}" auf der Seite aus.',
            'Finde bitte "{text}".',
        ],
    },
    "word_bbox": {
        "en": [
            'Give me the bounding box of the word "{text}".',
            'Highlight the region containing "{text}".',
            'What are the boundaries of "{text}"?',
            'Draw a box around "{text}".',
            'Select the full extent of "{text}".',
        ],
        "de": [
            'Gib mir die Begrenzung des Wortes "{text}".',
            'Markiere den Bereich, der "{text}" enthält.',
            'Wie sind die Grenzen von "{text}"?',
            'Zeichne einen Rahmen um "{text}".',
            'Wähle den gesamten Bereich von "{text}" aus.',
        ],
    },
    "line_start": {
        "en": [
            'Where does the line starting with "{text}" begin?',
            'Point to the start of the line beginning with "{text}".',
            'Can you find the left edge of the line that starts with "{text}"?',
            'Click at the beginning of the line starting "{text}".',
            'Show me where the line with "{text}" starts.',
        ],
        "de": [
            'Wo beginnt die Zeile, die mit "{text}" anfängt?',
            'Zeige auf den Anfang der Zeile, die mit "{text}" beginnt.',
            'Kannst du den linken Rand der Zeile finden, die mit "{text}" beginnt?',
            'Klicke auf den Anfang der Zeile, die mit "{text}" beginnt.',
            'Zeig mir, wo die Zeile mit "{text}" beginnt.',
        ],
    },
    "line_end": {
        "en": [
            'Where does the line ending with "{text}" finish?',
            'Point to the end of the line that ends with "{text}".',
            'Can you find the right edge of the line ending in "{text}"?',
            'Click at the end of the line that finishes with "{text}".',
            'Show me where the line with "{text}" ends.',
        ],
        "de": [
            'Wo endet die Zeile, die mit "{text}" aufhört?',
            'Zeige auf das Ende der Zeile, die mit "{text}" endet.',
            'Kannst du den rechten Rand der Zeile finden, die mit "{text}" endet?',
            'Klicke auf das Ende der Zeile, die mit "{text}" endet.',
            'Zeig mir, wo die Zeile mit "{text}" endet.',
        ],
    },
}

LANGUAGES = ("en", "de", "fr", "es", "it", "nl")

POINT_VERBS = {
    "en": ["Click on {ref}.", "Point to {ref}.", "Where is {ref} located?"],
    "de": ["Klicke auf {ref}.", "Zeige auf {ref}.", "Wo befindet sich {ref}?"],
    "fr": ["Cliquez sur {ref}.", "Montrez {ref}.", "Où se trouve {ref}?"],
    "es": ["Haz clic en {ref}.", "Señala {ref}.", "¿Dónde está {ref}?"],
    "it": ["Fai clic su {ref}.", "Indica {ref}.", "Dove si trova {ref}?"],
    "nl": ["Klik op {ref}.", "Wijs naar {ref}.", "Waar bevindt zich {ref}?"],
}

BBOX_VERBS = {
    "en": [
        "Draw a box around {ref}.",
        "Highlight the region of {ref}.",
        "Give me the bounding box of {ref}.",
    ],
    "de": [
        "Zeichne einen Rahmen um {ref}.",
        "Markiere den Bereich von {ref}.",
        "Gib mir die Begrenzung von {ref}.",
    ],
    "fr": [
        "Dessinez un cadre autour de {ref}.",
        "Surlignez la zone de {ref}.",
        "Donnez-moi le cadre englobant de {ref}.",
    ],
    "es": [
        "Dibuja un recuadro alrededor de {ref}.",
        "Resalta la región de {ref}.",
        "Dame el cuadro delimitador de {ref}.",
    ],
    "it": [
        "Disegna un riquadro attorno a {ref}.",
        "Evidenzia la regione di {ref}.",
        "Dammi il riquadro di delimitazione di {ref}.",
    ],
    "nl": [
        "Teken een kader rond {ref}.",
        "Markeer het gebied van {ref}.",
        "Geef me het begrenzingsvak van {ref}.",
    ],
}

# Occurrence disambiguation ("the second X", "das 2. Vorkommen von X") -
# used whenever the anchor text appears more than once on the page, so the
# instruction pins down WHICH instance is meant (real pointerbench-text
# does exactly this - see progress.md section 4d). Word ordinals cover the
# common 1..5; beyond that a numeric ordinal notation is used ("12th" /
# "12." style), which is what a real UI instruction would do anyway.
ORDINAL_WORDS = {
    "en": {1: "first", 2: "second", 3: "third", 4: "fourth", 5: "fifth"},
    "de": {1: "erste", 2: "zweite", 3: "dritte", 4: "vierte", 5: "fünfte"},
    "fr": {1: "première", 2: "deuxième", 3: "troisième", 4: "quatrième", 5: "cinquième"},
    "es": {1: "primera", 2: "segunda", 3: "tercera", 4: "cuarta", 5: "quinta"},
    "it": {1: "prima", 2: "seconda", 3: "terza", 4: "quarta", 5: "quinta"},
    "nl": {1: "eerste", 2: "tweede", 3: "derde", 4: "vierde", 5: "vijfde"},
}

OCCURRENCE_FRAMES = {
    "en": ['the {ordinal} "{text}"', 'the {ordinal} occurrence of "{text}"'],
    "de": ['das {ordinal} "{text}"', 'das {ordinal} Vorkommen von "{text}"'],
    "fr": ['le {ordinal} "{text}"', 'la {ordinal} occurrence de "{text}"'],
    "es": ['el {ordinal} "{text}"', 'la {ordinal} aparición de "{text}"'],
    "it": ['il {ordinal} "{text}"', 'la {ordinal} occorrenza di "{text}"'],
    "nl": ['de {ordinal} "{text}"', 'het {ordinal} voorkomen van "{text}"'],
}


def _ordinal_word(lang: str, n: int) -> str:
    word = ORDINAL_WORDS[lang].get(n)
    if word:
        return word
    if lang == "en":
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(n % 10 if not 10 <= n % 100 <= 20 else 0, "th")
        return f"{n}{suffix}"
    return f"{n}."


def _occ_ref(lang: str, text: str, n: int, rng) -> str:
    frame = rng.choice(OCCURRENCE_FRAMES[lang])
    return frame.format(ordinal=_ordinal_word(lang, n), text=text)


def _maybe_occ(lang: str, kw: dict) -> str:
    """The quoted anchor text, ordinal-qualified when kw carries an
    occurrence index."""
    n = kw.get("occurrence")
    if n:
        return _occ_ref(lang, kw["text"], n, kw["rng"])
    return f'"{kw["text"]}"'


CHAR_NOUN = {"en": "the character", "de": "das Zeichen", "fr": "le caractère", "es": "el carácter", "it": "il carattere", "nl": "het teken"}
IN_WORD = {"en": "in", "de": "in", "fr": "dans", "es": "en", "it": "in", "nl": "in"}
BETWEEN = {"en": "between", "de": "zwischen", "fr": "entre", "es": "entre", "it": "tra", "nl": "tussen"}
AND = {"en": "and", "de": "und", "fr": "et", "es": "y", "it": "e", "nl": "en"}
JUST_BEFORE = {"en": "just before", "de": "kurz vor", "fr": "juste avant", "es": "justo antes de", "it": "appena prima di", "nl": "net voor"}
JUST_AFTER = {"en": "just after", "de": "kurz nach", "fr": "juste après", "es": "justo después de", "it": "appena dopo", "nl": "net na"}
PARA_NOUN = {"en": "the paragraph", "de": "der Absatz", "fr": "le paragraphe", "es": "el párrafo", "it": "il paragrafo", "nl": "de alinea"}
LINE_NOUN = {"en": "the line", "de": "die Zeile", "fr": "la ligne", "es": "la línea", "it": "la riga", "nl": "de regel"}
PARA_START_NOUN = {"en": "the start of the paragraph", "de": "der Anfang des Absatzes", "fr": "le début du paragraphe", "es": "el inicio del párrafo", "it": "l'inizio del paragrafo", "nl": "het begin van de alinea"}
PARA_END_NOUN = {"en": "the end of the paragraph", "de": "das Ende des Absatzes", "fr": "la fin du paragraphe", "es": "el final del párrafo", "it": "la fine del paragrafo", "nl": "het einde van de alinea"}
SENTENCE_END_NOUN = {"en": "the end of the sentence", "de": "das Ende des Satzes", "fr": "la fin de la phrase", "es": "el final de la oración", "it": "la fine della frase", "nl": "het einde van de zin"}
STRUCTURAL_NOUN = {"en": "the page title", "de": "der Seitentitel", "fr": "le titre de la page", "es": "el título de la página", "it": "il titolo della pagina", "nl": "de paginatitel"}
BLANK_LINE_NOUN = {"en": "the blank line between the paragraphs", "de": "die leere Zeile zwischen den Absätzen", "fr": "la ligne vide entre les paragraphes", "es": "la línea en blanco entre los párrafos", "it": "la riga vuota tra i paragrafi", "nl": "de lege regel tussen de alinea's"}

FIELD_LABELS = {
    "invoice_number": {"en": "the invoice number", "de": "die Rechnungsnummer", "fr": "le numéro de facture", "es": "el número de factura", "it": "il numero di fattura", "nl": "het factuurnummer"},
    "invoice_date": {"en": "the invoice date", "de": "das Rechnungsdatum", "fr": "la date de facture", "es": "la fecha de la factura", "it": "la data della fattura", "nl": "de factuurdatum"},
    "invoice_due_date": {"en": "the due date", "de": "das Fälligkeitsdatum", "fr": "la date d'échéance", "es": "la fecha de vencimiento", "it": "la data di scadenza", "nl": "de vervaldatum"},
    "invoice_subtotal": {"en": "the subtotal", "de": "die Zwischensumme", "fr": "le sous-total", "es": "el subtotal", "it": "il subtotale", "nl": "het subtotaal"},
    "invoice_tax": {"en": "the tax amount", "de": "den Steuerbetrag", "fr": "le montant de la taxe", "es": "el importe del impuesto", "it": "l'importo dell'imposta", "nl": "het belastingbedrag"},
    "invoice_tax_id": {"en": "the tax ID", "de": "die Steuernummer", "fr": "le numéro fiscal", "es": "el número de identificación fiscal", "it": "il codice fiscale", "nl": "het btw-nummer"},
    "invoice_total": {"en": "the total amount", "de": "den Gesamtbetrag", "fr": "le montant total", "es": "el importe total", "it": "l'importo totale", "nl": "het totaalbedrag"},
    "invoice_totals": {"en": "the totals line", "de": "die Summenzeile", "fr": "la ligne des totaux", "es": "la línea de totales", "it": "la riga dei totali", "nl": "de totaalregel"},
    "invoice_sender": {"en": "the sender's name", "de": "den Namen des Absenders", "fr": "le nom de l'expéditeur", "es": "el nombre del remitente", "it": "il nome del mittente", "nl": "de naam van de afzender"},
    "invoice_sender_city": {"en": "the sender's city", "de": "die Stadt des Absenders", "fr": "la ville de l'expéditeur", "es": "la ciudad del remitente", "it": "la città del mittente", "nl": "de stad van de afzender"},
    "invoice_sender_zip": {"en": "the sender's postal code", "de": "die Postleitzahl des Absenders", "fr": "le code postal de l'expéditeur", "es": "el código postal del remitente", "it": "il codice postale del mittente", "nl": "de postcode van de afzender"},
    "invoice_recipient": {"en": "the recipient's name", "de": "den Namen des Empfängers", "fr": "le nom du destinataire", "es": "el nombre del destinatario", "it": "il nome del destinatario", "nl": "de naam van de ontvanger"},
    "invoice_recipient_city": {"en": "the recipient's city", "de": "die Stadt des Empfängers", "fr": "la ville du destinataire", "es": "la ciudad del destinatario", "it": "la città del destinatario", "nl": "de stad van de ontvanger"},
    "invoice_recipient_zip": {"en": "the recipient's postal code", "de": "die Postleitzahl des Empfängers", "fr": "le code postal du destinataire", "es": "el código postal del destinatario", "it": "il codice postale del destinatario", "nl": "de postcode van de ontvanger"},
    "invoice_bic": {"en": "the BIC code", "de": "den BIC-Code", "fr": "le code BIC", "es": "el código BIC", "it": "il codice BIC", "nl": "de BIC-code"},
    "invoice_iban": {"en": "the IBAN", "de": "die IBAN", "fr": "l'IBAN", "es": "el IBAN", "it": "l'IBAN", "nl": "het IBAN"},
    "invoice_bank_details": {"en": "the bank details", "de": "die Bankverbindung", "fr": "les coordonnées bancaires", "es": "los datos bancarios", "it": "i dati bancari", "nl": "de bankgegevens"},
    "invoice_email": {"en": "the email address", "de": "die E-Mail-Adresse", "fr": "l'adresse e-mail", "es": "la dirección de correo electrónico", "it": "l'indirizzo email", "nl": "het e-mailadres"},
    "invoice_phone": {"en": "the phone number", "de": "die Telefonnummer", "fr": "le numéro de téléphone", "es": "el número de teléfono", "it": "il numero di telefono", "nl": "het telefoonnummer"},
    "invoice_line_item": {"en": "a line item", "de": "eine Rechnungsposition", "fr": "une ligne de facturation", "es": "una línea de factura", "it": "una voce della fattura", "nl": "een factuurregel"},
    "invoice_line_items": {"en": "the line items table", "de": "die Tabelle der Rechnungspositionen", "fr": "le tableau des lignes de facturation", "es": "la tabla de líneas de factura", "it": "la tabella delle voci di fattura", "nl": "de tabel met factuurregels"},
}


def _ref_char(lang, **kw):
    return f'{CHAR_NOUN[lang]} "{kw["ch"]}" {IN_WORD[lang]} "{kw["text"]}"'


def _ref_between_words(lang, **kw):
    first = _maybe_occ(lang, {**kw, "text": kw["text1"]})
    return f'{BETWEEN[lang]} {first} {AND[lang]} "{kw["text2"]}"'


def _ref_caret_before(lang, **kw):
    return f'{JUST_BEFORE[lang]} {_maybe_occ(lang, kw)}'


def _ref_caret_after(lang, **kw):
    return f'{JUST_AFTER[lang]} {_maybe_occ(lang, kw)}'


def _ref_caret_between_chars(lang, **kw):
    return f'{BETWEEN[lang]} "{kw["ch1"]}" {AND[lang]} "{kw["ch2"]}" {IN_WORD[lang]} {_maybe_occ(lang, kw)}'


def _ref_paragraph_bbox(lang, **kw):
    return f'{PARA_NOUN[lang]}: "{kw["text"]}"'


def _ref_paragraph_start(lang, **kw):
    return f'{PARA_START_NOUN[lang]} "{kw["text"]}"'


def _ref_paragraph_end(lang, **kw):
    return f'{PARA_END_NOUN[lang]} "{kw["text"]}"'


def _ref_line_bbox(lang, **kw):
    return f'{LINE_NOUN[lang]}: "{kw["text"]}"'


def _ref_sentence_boundary(lang, **kw):
    return f'{SENTENCE_END_NOUN[lang]} "{kw["text"]}"'


def _ref_structural(lang, **kw):
    # Quotes the literal title text (colon-style, matching line_bbox/
    # paragraph_bbox's convention) so the planner - which has no vision -
    # has something to echo back as anchor_phrase. See progress.md section 4b.
    text = kw.get("text")
    if not text:
        return STRUCTURAL_NOUN[lang]
    return f'{STRUCTURAL_NOUN[lang]}: "{text}"'


def _ref_blank_line(lang, **kw):
    return BLANK_LINE_NOUN[lang]


def _ref_field(lang, **kw):
    return FIELD_LABELS[kw["field"]][lang]


REF_BUILDERS = {
    "char_center": _ref_char,
    "char_bbox": _ref_char,
    "punctuation": _ref_char,
    "between_words": _ref_between_words,
    "caret_before_word": _ref_caret_before,
    "caret_after_word": _ref_caret_after,
    "caret_between_chars": _ref_caret_between_chars,
    "paragraph_bbox": _ref_paragraph_bbox,
    "paragraph_start": _ref_paragraph_start,
    "paragraph_end": _ref_paragraph_end,
    "line_bbox": _ref_line_bbox,
    "sentence_boundary": _ref_sentence_boundary,
    "structural_text": _ref_structural,
    "blank_line": _ref_blank_line,
}
for _field_key in FIELD_LABELS:
    REF_BUILDERS[_field_key] = _ref_field

# Categories whose answer_type is "bbox"; every other category (including all
# invoice field categories except the line-items table) is a point target.
BBOX_CATEGORIES = {
    "word_bbox", "char_bbox", "paragraph_bbox", "line_bbox", "structural_text",
    "invoice_line_items",
}


def phrase(category: str, language: str, rng, **kwargs) -> str:
    kwargs.setdefault("rng", rng)  # occurrence frames need it for variety

    # Occurrence-disambiguated word_center bypasses the hand-written
    # TEMPLATES (which have no slot for an ordinal) and composes the same
    # verb-frame + referent construction the Sprint-3 categories use.
    if category == "word_center" and kwargs.get("occurrence"):
        ref = _occ_ref(language, kwargs["text"], kwargs["occurrence"], rng)
        return rng.choice(POINT_VERBS[language]).format(ref=ref)

    if category in TEMPLATES:
        options = TEMPLATES[category].get(language) or TEMPLATES[category]["en"]
        tmpl = rng.choice(options)
        return tmpl.format(**{k: v for k, v in kwargs.items() if k != "rng"})

    builder = REF_BUILDERS[category]
    ref = builder(language, **kwargs)
    verbs = BBOX_VERBS if category in BBOX_CATEGORIES else POINT_VERBS
    tmpl = rng.choice(verbs[language])
    return tmpl.format(ref=ref)
